version: '3.8'

services:
  legacy-db:
    image: postgres:15
    container_name: legacy-crm-db
    environment:
      POSTGRES_DB: legacy_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - legacy_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d legacy_crm"]
      interval: 5s
      timeout: 5s
      retries: 10

  legacy-app:
    build: ./legacy-crm
    container_name: legacy-crm-app
    ports:
      - "8080:8080"
    depends_on:
      legacy-db:
        condition: service_healthy  # Wait for DB health check
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://legacy-db:5432/legacy_crm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  legacy_data: