spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8000

logging:
  level:
    com.crm.gateway: DEBUG
    root: INFO

# Service URLs for routing
legacy:
  service:
    url: http://legacy-app:8080