spring:
  application:
    name: api-gateway

server:
  port: 8000

logging:
  level:
    com.crm.gateway: DEBUG
    root: INFO

# Service URLs for routing
legacy:
  service:
    url: http://legacy-app:8080

customer:
  service:
    url: http://customer-service:8081

order:
  service:
    url: http://order-service:8082