spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/legacy_crm}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  sql:
    init:
      mode: always
      continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.boot.autoconfigure.sql.init: DEBUG
    root: INFO