spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/customer_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8081

logging:
  level:
    com.crm.customer: DEBUG